### ISSUE TITLE
Asymmetric Encryption

### ISSUE THREAD

**Issue by flyfishMT** [johnsheehan/jwt#15] opened 2015-03-24 21:33 UTC
Could you add asymmetric encryption?  That seems to be all that is missing to support JWS - JSON Web Signature.

**Comment by mikelehen** [comment] 2015-05-01 04:23
Dupe of #9. This is definitely something missing and I'd welcome a pull request, but I'm not likely to have time to tackle this myself in the short-term.

**Closed by mikelehen** 2015-05-01 04:23 UTC
